# Generated by Django 3.2.3 on 2021-06-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Civil', '0002_auto_20210615_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phd',
            name='academic_year',
        ),
    ]
