# Generated by Django 3.1.4 on 2021-06-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Civil', '0004_auto_20210618_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleScholarCitationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=100)),
                ('teacher_name', models.CharField(default='', max_length=100)),
                ('designation', models.CharField(default='', max_length=100)),
                ('citations_2015', models.IntegerField(default=0)),
                ('h_index_2015', models.IntegerField(default=0)),
                ('i_10_2015', models.IntegerField(default=0)),
                ('citations_all', models.IntegerField(default=0)),
                ('h_index_all', models.IntegerField(default=0)),
                ('i_10_all', models.IntegerField(default=0)),
                ('cited_publication', models.IntegerField(default=0)),
                ('reported_publication', models.IntegerField(default=0)),
                ('academic_year', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
