# Generated by Django 3.1.4 on 2021-05-18 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0002_auto_20210518_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTechStudentData',
            fields=[
                ('name', models.CharField(default='', max_length=100)),
                ('PRN', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('gender', models.CharField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=200)),
                ('admission_date', models.DateField(default=datetime.date.today)),
                ('category', models.CharField(default='', max_length=40)),
                ('fees_paid', models.PositiveBigIntegerField(default=0)),
                ('branch', models.CharField(default='', max_length=40)),
                ('clg_shift', models.CharField(default='1', max_length=20)),
                ('CET_Score', models.FloatField(default=None)),
                ('admission_type', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
