# Generated by Django 3.1.4 on 2021-06-02 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0005_auto_20210526_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPublished',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_faculty', models.CharField(default='', max_length=100)),
                ('title_of_book', models.CharField(default='', max_length=100)),
                ('name_of_publisher', models.CharField(default='', max_length=100)),
                ('date_publication', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyCompletedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(default='', max_length=100)),
                ('title_course', models.CharField(default='', max_length=100)),
                ('starting_date', models.DateField(default=datetime.date.today)),
                ('completion_date', models.DateField(default=datetime.date.today)),
                ('mode', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('name_faculty', models.CharField(default='', max_length=100)),
                ('patent_no', models.IntegerField(default=0)),
                ('date_of_file', models.DateField(default=datetime.date.today)),
                ('awarded', models.BooleanField(default=False)),
            ],
        ),
    ]
