# Generated by Django 3.1.4 on 2021-06-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0006_bookpublished_facultycompletedcourse_patents'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpublished',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='facultycompletedcourse',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patents',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
