# Generated by Django 3.1.4 on 2021-06-16 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0010_remove_phd_academic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideforPHD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=100)),
                ('student_name', models.CharField(default='', max_length=100)),
                ('registration_date', models.DateField(default=datetime.date.today)),
                ('title_thesis', models.CharField(default='', max_length=500)),
                ('guide_name', models.CharField(default='', max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('comment_on_thesis', models.CharField(default='', max_length=20)),
                ('type_of_phd', models.CharField(default='other', max_length=20)),
                ('completion_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AddField(
            model_name='phd',
            name='faculty_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookpublished',
            name='title_of_book',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='facultycompletedcourse',
            name='title_course',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='patents',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='phd',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='researchpapermain',
            name='area_of_research',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='researchpapermain',
            name='details_of_paper',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='researchpapermain',
            name='publication_details',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
