# Generated by Django 3.1.4 on 2021-06-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0012_googlescholarcitationdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='joining_date',
        ),
    ]
