# Generated by Django 3.1.4 on 2021-06-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0013_remove_teacher_joining_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btechstudentdata',
            name='admission_date',
        ),
    ]
