# Generated by Django 3.2.3 on 2021-06-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0015_eventconductedordelivered_guestlecorganizedordelivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventconductedordelivered',
            name='academic_year',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guestlecorganizedordelivered',
            name='academic_year',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
