# Generated by Django 3.2.3 on 2021-06-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0017_auto_20210618_2225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventConductedOrDelivered',
            new_name='EventConductedOrAttended',
        ),
    ]
