# Generated by Django 3.1.4 on 2021-06-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0005_googlescholarcitationdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btechstudentdata',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='joining_date',
        ),
    ]
