# Generated by Django 3.2.3 on 2021-06-18 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0006_auto_20210618_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventConductedOrAttended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=100)),
                ('teacher_name', models.CharField(default='', max_length=100)),
                ('nameof_event', models.CharField(default='', max_length=100)),
                ('event_details', models.CharField(default='', max_length=100)),
                ('starting_date', models.DateField(default=datetime.date.today)),
                ('ending_date', models.DateField(default=datetime.date.today)),
                ('type_of_event', models.CharField(default='', max_length=100)),
                ('academic_year', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GuestLecOrganizedOrDelivered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=100)),
                ('teacher_name', models.CharField(default='', max_length=100)),
                ('place', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('starting_date', models.DateField(default=datetime.date.today)),
                ('ending_date', models.DateField(default=datetime.date.today)),
                ('type', models.CharField(default='', max_length=100)),
                ('academic_year', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
